services:
  config-server:
    build: .
    container_name: finwise-config-server
    ports:
      - "9901:9901"
    networks:
      - finwise-network

networks:
  finwise-network:
    driver: bridge

