server:
  port: 9901

spring:
  profiles:
    active: native
  application:
    name: finwise-config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations