spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes[0]:
        id: user-service
        uri: lb://user-service
        predicates[0]: Path=/api/v1/users/**

server:
  port: 443
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: qW_c!;zne"tvD1qGi?K]m("!4)Vbts>Q
    key-store-password: ${server.ssl.key-password}


eureka:
  instance:
    hostname: discovery-server
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/



management:
  tracing:
    sampling:
      probability: 1.0