spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true

server:
  port: 443
  ssl:
    enabled: true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: qW_c!;zne"tvD1qGi?K]m("!4)Vbts>Q
    key-store-password: ${server.ssl.key-password}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9902/eureka/

management:
  tracing:
    sampling:
      probability: 1.0